CREATE DATABASE DC_BACKEND_DB;
GO

USE DC_BACKEND_DB;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CUSTOMER')
BEGIN
    CREATE TABLE CUSTOMER
    (
        USERID UNIQUEIDENTIFIER PRIMARY KEY,
		USERNAME NVARCHAR(30) NOT NULL,
		EMAIL NVARCHAR(20) NOT NULL,
		FIRST_NAME NVARCHAR(20) NOT NULL,
		LAST_NAME NVARCHAR(20) NOT NULL,
		CREATED_ON DATETIME NOT NULL,
		IS_ACTIVE BIT NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUPPLIER')
BEGIN
	CREATE TABLE SUPPLIER 
	(
		SUPPLIER_ID UNIQUEIDENTIFIER PRIMARY KEY,
		SUPPLIER_NAME NVARCHAR(50) NOT NULL,
		CREATED_ON DATETIME NOT NULL,
		IS_ACTIVE BIT NOT NULL
	);

END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PRODUCT')
BEGIN
	CREATE TABLE PRODUCT 
	(
		PRODUCT_ID UNIQUEIDENTIFIER PRIMARY KEY,
		PRODUCT_NAME NVARCHAR(50) NOT NULL,
		UNIT_PRICE DECIMAL(18, 2) NOT NULL,
		SUPPLIER_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SUPPLIER(SUPPLIER_ID),
		CREATED_ON DATETIME NOT NULL,
		IS_ACTIVE BIT NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER')
BEGIN
	CREATE TABLE [ORDER] (
		ORDER_ID UNIQUEIDENTIFIER PRIMARY KEY,
		PRODUCT_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
		ORDER_STATUS INT NOT NULL,
		ORDER_TYPE INT NOT NULL,
		ORDER_BY UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CUSTOMER(USERID),
		ORDER_ON DATETIME NOT NULL,
		SHIPPED_ON DATETIME NULL,
		IS_ACTIVE BIT NOT NULL
	);

END
GO

IF NOT EXISTS (SELECT * FROM sys.procedures WHERE name = 'GetActiveOrdersByCustomer')
BEGIN
    EXEC('
    CREATE PROCEDURE GetActiveOrdersByCustomer
		@USERID UNIQUEIDENTIFIER
	AS
	BEGIN
		SELECT 
			O.ORDER_ID,
			O.ORDER_STATUS,
			O.ORDER_TYPE,
			O.ORDER_ON,
			O.SHIPPED_ON,
			P.PRODUCT_ID,
			P.PRODUCT_NAME,
			P.UNIT_PRICE,
			S.SUPPLIER_ID,
			S.SUPPLIER_NAME
		FROM [ORDER] AS O
		INNER JOIN PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
		INNER JOIN SUPPLIER AS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
		WHERE O.ORDER_BY = @USERID AND O.IS_ACTIVE = 1
	END
    ')
END
GO



